# Generated by Django 4.2.6 on 2023-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='coverlater',
            field=models.TextField(help_text='please enter your note here...', max_length=500),
        ),
    ]
